### PR TITLE
added a flag in the ArangoDeployment K8s spec to turn off finalizers …

### PR DESCRIPTION
**Pull request by rglyons**
…in ArangoDeployments and their PVCs

The default behavior is still to apply, validate, and respect finalizers on the ArangoDeployment resources, however this behavior can be overwritten with the `enableFinalizers` boolean value in the ArangoDeployment spec. In the case that `enableFinalizers: false` is provided in the ArangoDeployment yaml spec, all agents, coordinators, db servers, and pvcs are brought up with no finalizers. This allows users to teardown entire clusters in any order, and was implemented to serve the use case of single-step (unordered) namespace teardowns in kubernetes. 

Please let me know if I have missed any steps (writing/running some test suite, etc.). I am happy to work with you to get this merged, because maintaining a custom fork of this repo could be cumbersome. 

related to #251 

NOTE: if this PR is accepted and merged, this documentation page will need to be updated - 
https://docs.arangodb.com/devel/Manual/Deployment/Kubernetes/DeploymentResource.html#specsyncexternalaccesstype-string

### CODE REVIEW

**Comment by OmarAyo** [comment]
Hi @rglyons 

Thanks a lot for your improvements.  In order to merge it, we need a signed CLA.  We are using an Apache 2 CLA for ArangoDB and its sub-components, which can be found here: https://www.arangodb.com/documents/cla.pdf

Could you please sign, scan and email it to cla@arangodb.com

Thanks a lot

Omar Ayoubi

**Comment by ewoutp** [comment]
hi @rglyons 
While I understand the intent of this PR I have serious concerns about.
Without the finalizers, there is no way we can guarantee data safety.

We'll discuss what we want to do with this and then come back on it.

**Comment by rglyons** [comment]
@ewoutp I understand your concerns and why your design includes finalizers. This PR does not change the default behavior - finalizers are still applied _unless_ the `enableFinalizers: false` option is provided in the ArangoDeployment yaml. This gives the user the option to forego that data protection _if they choose to do so_. 

Ideally, the finalizers remain, but full teardown is controlled so that the system never ends up in a frozen state, e.g. when the operator completes teardown before any ArangoDB resources. If that were implemented then this PR would be obsolete. 

I'm looking forward to hearing about the conclusions from your discussions.

**Comment by neunhoef** [comment]
Hi @rglyons,
after some discussions we have decided against incorporating this PR, sorry for this.

Here is our thinking:

This would be a switch which set to `false` would seriously harm the resilience of the system, since deployed resources could be deleted without warning, which can very easily result in data loss. This is the worst that can ever happen to a database. We think that once this option is available, we will eventually have people who have bought support and still use this flag. This can lead to extremely bad situations, which we have to avoid at all cost. And even if we find this usage before it is too late, with this PR we cannot even change the deployment easily after the fact, since one cannot edit the flag after deployment. Implementing this functionality would be an undue burden for development and unduly complicate things.

We understand that this has the potential to cause inconveniences during development, but we think this can be avoided easily by removing all custom resources before removing the operator deployment itself. So in the end, this is a judgement weighing potential business risk against developer convenience.

If you have a scenario which we have overlooked in this reasoning and which would create a huge inconvenience, please let us know. I am closing this for now, feel free to open again if there are new aspects.

Cheers,
  Max.

**Pull request closed without merging**
