### PR TITLE
Bump yaml.v3 version to fix CVE

### LINKED ISSUE #1273: High vulnerability in gopkg.in/yaml.v3 module - Update to version 3.0.0 needed
Hi there,

I hope this message finds you well. I wanted to reach out to you regarding a potential security issue that has been reported in the `gopkg.in/yaml.v3` module.

Recently, a high vulnerability was reported in this module, and I wanted to bring it to your attention in case you haven't already seen it. The details of the vulnerability can be found here: https://github.com/advisories/GHSA-hp87-p4gw-j4gq.

To address this issue, I strongly recommend updating the `gopkg.in/yaml.v3` module to version 3.0.0.
I was wondering if you have any information on when release 1.2.25 with the fix is scheduled.

Thank you for your attention to this matter, and happy coding! 💪🏻😎

### PR DESCRIPTION
**Pull request by nikita-vanyasin**
Fixes #1273

### CODE REVIEW

**Review by informalict — APPROVED** [review]
lgtm

**Comment by jbrizio** [comment]
Thanks @nikita-vanyasin for the pull request opened. I hope this change will be introduced in the next release to solve the mentioned CVEs.

**Comment by ajanikow** [comment]
Already in master. Also, this dependency is not used in Operator - only by the internal module used to generate yamls

**Comment by jbrizio** [comment]
@ajanikow when is scheduled the release of the new version with this fix introduced? Thanks again.

**Pull request closed without merging**
