### PR TITLE
Update the helm install and upgrade README sections to use the new helm repo

### PR DESCRIPTION
**Pull request by mysticaltech**
Thanks to the amazing work of @informalict in #562, you now have your own automatically maintained helm repo over at https://arangodb.github.io/kube-arangodb and deployed from your gh-pages branch! So the readme can be simplified a lot, especially the upgrade section!

### CODE REVIEW

**Comment by ajanikow** [comment]
Hello!

It will be updated during the next release by automation.

Best Regards,
Adam.

**Comment by mysticaltech** [comment]
Awesome!

**Comment by mysticaltech** [comment]
Have signed the CLA.

**Comment by mysticaltech** [comment]
However, this seems to have stopped working; the helm repo is not up to date and not working as it should. The latest version found is 1.2.8, and the `crd` chart won't install. It is a shame that you folks are still ok to use helm without a proper repo; why use a custom flow when there is such a well-established one?! I will close that PR for now.

**Comment by mysticaltech** [comment]
@informalict FYI, the repo is no longer working, well, read above, please.

**Pull request closed without merging**
